# Generated by Django 4.1.7 on 2023-03-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_add_slug_to_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="adress",
            name="zip",
            field=models.CharField(default="00000", max_length=5),
            preserve_default=False,
        ),
    ]
