# Generated by Django 4.1.7 on 2023-03-25 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_add_zip_to_adress"),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection (title)
            VALUE ("collection1")
        """, """
            DELETE FROM store_collection
            WHERE title="collection1"
        """)
    ]
